NAME: ALPHA
CATEGORY_FILE_PATH: /home/DAVIDSON/hayavuzkara/Data/22Mg_16O_combo/category.json
N_POINTS: 16384
N_RENDERINGS: 8
PARTIAL_POINTS_PATH: /home/DAVIDSON/hayavuzkara/Data/22Mg_16O_combo/%s/partial/%s/%.npy
COMPLETE_POINTS_PATH: /home/DAVIDSON/hayavuzkara/Data/22Mg_16O_combo/%s/complete/%s.npy
CARS: FALSE